$initScript = <<SCRIPT
 yum install -y httpd
 systemctl enable httpd
 systemctl start httpd
 yum install java-1.8.0-openjdk-devel -y 
 yum install git -y
 yum install wget -y
 wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
 tar -xvf go1.12.7.linux-amd64.tar.gz
 cd go/src
 mkdir github.com
 cd ~ 
 echo 'export PATH="$PATH:/root/go/"' >> ~/.bashrc
 
 
 
 
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "usman"
  config.vm.network "private_network", ip: "192.168.56.100"
  
  config.vm.provision "shell", inline: $initScript
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end
  
end
